### ISSUE TITLE
probelms about evaluate on MOT16

### ISSUE THREAD

**Issue by Tclamber** [phil-bergmann/tracking_wo_bnw#10]
Thanks for sharing your great work ！I wondor what the input to evuluate Tracktor on MOT16 . MOT16 labels or MOT16-det-dpm-raw.

**Comment by timmeinhardt** [comment]
In order to run Tracktor on MOT16 you always need the `MOT16Labels` directory. However, MOT16 offers to sets of DPM public detections. If you want to run Tracktor on the non-filtered raw set of DPM detections you additionally need the `MOT16-det-dpm-raw` directory. Also see `src/tracktor/datasets/factory.py` for all available dataset and detection combinations.

**Comment by Tclamber** [comment]
Thanks fot your reply.  You mean it depends on the need of every tracker itself ?  raw detections or NMSed detections all are ok.

**Comment by timmeinhardt** [comment]
Different trackers might work better or worse with different sets of public detections. For MOT16 one is free to choose between the regular and raw DPM detections.

**Comment by Tclamber** [comment]
I see ,Thanks !

**Comment by timmeinhardt** [comment]
No problem. Can we close this issue?

**Comment by Ronales** [comment]
> 没问题。我们可以关闭这个问题吗？

Dear author,Where is your prerocess code for detection file (det.txt)?,I think raw detection file from motchallenge can't suit to decrease FP,FN. Can you tell me the detail of clean the raw detection file?thank you very much!

**Comment by Ronales** [comment]
> No problem. Can we close this issue?
Dear author,Where is your prerocess code for detection file (det.txt)?,I think raw detection file from motchallenge can't suit to decrease FP,FN. Can you tell me the detail of clean the raw detection file?thank you very much!

**Comment by timmeinhardt** [comment]
Are u referring to the MOT16 raw DPM detections? They come in the same format as the regular detections. The only difference is that the last NMS step was omitted. And yes, the raw detections can help to decrease FN but in turn might introduce some FP. Not sure if this answers your question.

**Comment by Ronales** [comment]
> Are u referring to the MOT16 raw DPM detections? They come in the same format as the regular detections. The only difference is that the last NMS step was omitted. And yes, the raw detections can help to decrease FN but in turn might introduce some FP. Not sure if this answers your question.

Dear author，but do you implement the nms step from the mot16 in the code for the original test data? Or you have used other methods to reduce the FP, FN from the original test data. Where is the code detail placed in your code?If you do not deal with the original detection data of mot16 and go directly to the data association effect is very bad.Thanks！

**Comment by timmeinhardt** [comment]
I am not sure if I understand your question correctly. What do you mean by the "original test data"? The testset which can only be evaluated by submitting to the challenge?

Our Tracktor applies multiple NMS steps on his own. However, in the case of MOT16 raw detections Tracktor is applied to a raw set of detections which were not filtered by NMS beforehand. But NMS is still applied in the Tracktor pipeline.

**Comment by Ronales** [comment]
> I am not sure if I understand your question correctly. What do you mean by the "original test data"? The testset which can only be evaluated by submitting to the challenge?
> 
> Our Tracktor applies multiple NMS steps on his own. However, in the case of MOT16 raw detections Tracktor is applied to a raw set of detections which were not filtered by NMS beforehand. But NMS is still applied in the Tracktor pipeline.

sorry，I forget instructed this concept，”original test data“ means the det.txt (train or test )provided detection results form motchallenge.net, these confidence scores some have under 0 ，when I use min confidence 0.1 or 0.3 to suppress this detection FP for good detection performance, but I never get good mota, only 44.5. I think good preprocess detection result can provide a good foundation, But I may be encounter problem in preprocessing this det.txt.so I want to ask you for your code realize detail.

**Comment by timmeinhardt** [comment]
We apply no preprocessing to the detection files. They are loaded as they are in our dataset code and then all further steps, e.g., classification and regression, are part of this codebase.

**Comment by Ronales** [comment]
> We apply no preprocessing to the detection files. They are loaded as they are in our dataset code (`src/tracktor/datasets/mot_sequence.py`) and then all further steps, e.g., classification and regression, are part of this codebase.

I get it，Thanks for your reply！

**Comment by timmeinhardt** [comment]
No worries. Can we close this issue?

**Comment by Tclamber** [comment]
Sorry . of course .we can close it.
