### ISSUE TITLE
Model file for Notebook

### ISSUE THREAD

**Issue by ayushrox** [phil-bergmann/tracking_wo_bnw#101]
From where do I get the  model_epoch_27.model file?

**Comment by timmeinhardt** [comment]
The notebook is only a starting point for training your model thats why I accidentally left the two lines in there. I removed the lines and now you can use the notebook to train a model from scratch to 27 epochs and run it with Tracktor.

**Comment by timmeinhardt** [comment]
Can we close this issue?
