### ISSUE TITLE
Why run predict_boxes on current frame twice

### ISSUE THREAD

**Issue by blueMoon7** [phil-bergmann/tracking_wo_bnw#102]
Hi,

When the code is set to use `public_detections`, why would you call `predict_boxes` on detections? This [line](https://github.com/phil-bergmann/tracking_wo_bnw/blob/master/src/tracktor/tracker.py#L266) 
```
		if self.public_detections:
			dets = blob['dets'].squeeze(dim=0)
			if dets.nelement() > 0:
				boxes, scores = self.obj_detect.predict_boxes(dets)
```
It makes sense to only resize the boxes, but I'm confused why it is necessary to again run detection.

Thanks

**Comment by starkgate** [comment]
By twice, do you mean once in `regress_tracks` and once in `step`?

From what I understand, the idea is to run `predict_boxes` once on the entire frame (at time-step `t`) to get the initial predictions. Then you compare each prediction to the previous frame's (at time-step `t-1`) predictions (stored as tracks) to see if any match enough to be considered part of the same track.

**Comment by timmeinhardt** [comment]
@starkgate is correct. Can we close this issue?
