### ISSUE TITLE
Do we need to normalize the image before feeding into the re-id resnet?

### ISSUE THREAD

**Issue by AlanZTY** [phil-bergmann/tracking_wo_bnw#103]
I found a yaml file coming with pretrained weights of re-id network. It has stated commonly used normalization
 normalize_mean:
    - 0.485
    - 0.456
    - 0.406
    normalize_std:
    - 0.229
    - 0.224
    - 0.225
However, in the test time, I found that the image is not normalized. Since I am about to use this as a feature extractor, I want to be careful here. Do we actually need to normalize the image?

**Comment by timmeinhardt** [comment]
The images are normalized and test time in the corresponding dataset code. So yes, you have to normalize them as well if you want to use our reID network as a feature extractor.

**Comment by timmeinhardt** [comment]
Can we close this issue?
