### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by Leo63963** [phil-bergmann/tracking_wo_bnw#104]
Hi ! 
Thanks for the great work.
I run the code with my detection results, and find an **IndexError** as below:

Traceback (most recent call last):
  File "experiments/scripts/test_tracktor.py", line 106, in <module>
    tracker.step(frame)
  File "/home/lee/Detection/mmdetection/tracking_wo_bnw/src/tracktor/tracker.py", line 299, in step
    person_scores = self.regress_tracks()
  File "/home/lee/Detection/mmdetection/tracking_wo_bnw/src/tracktor/tracker.py", line 85, in regress_tracks
    t.score = scores[i]
IndexError: index 10 is out of bounds for axis 0 with size 10

Do you have any idea about it?
Many thanks.

**Comment by Leo63963** [comment]
Hi !
Update of this bug.
By changing the vaule of **detection_nms_thresh**, the problem solved.
Do you have any idea about the reason?
Many thanks.

**Comment by Catchen98** [comment]
I have the same problem,can you tell me how to solve it?,thanks

**Comment by timmeinhardt** [comment]
Does the error also happen for private results with the model we provided?

**Comment by Leo63963** [comment]
Hi Tim and Catchen
1. I have not tried the private detector, therefore I have no idea about that.
2. I solved it by changing the nms_threshold to 1.0 and score for 0.0, you can try if it works.

**Comment by timmeinhardt** [comment]
You are writing "with my detection results". This means with private detections or are you loading your private detections as public detection. The first thing I would try is running the unchanged code, i.e., the Tracktor model, in to see if this also occurs without your changes. 

Changing nms_threshold and the score threshold means none of those will get removed. Maybe our default parameters resulted in filtering out all of your detections. Then this is all just a hyperparamter issue. 

@Catchen98 Please check if this is the case for you and you only have to adjust the hyperparameters.

**Comment by Catchen98** [comment]
> 您正在写“有我的检测结果”。这意味着使用私密检测，或者您是将私密检测作为公共检测加载。我要尝试的第一件事是运行未更改的代码，即Tracktor模型，以查看是否在不做任何更改的情况下也发生了这种情况。
> 
> 如您所描述的那样更改nms_threshold和得分阈值意味着没有任何检测将被删除。也许我们的默认参数导致您的所有检测结果被过滤掉了。然后，这仅仅是一个超参数问题。
> 
> @ Catchen98请检查是否适合您，您只需要调整超参数。

Thank you for your reply, I will try the method you said

**Comment by Catchen98** [comment]
> You are writing "with my detection results". This means with private detections or are you loading your private detections as public detections. The first thing I would try is running the unchanged code, i.e., the Tracktor model, to see if this also occurs without your changes.
> 
> Changing nms_threshold and the score threshold as you described means none of the detections will get removed. Maybe our default parameters resulted in filtering out all of your detections. Then this is all just a hyperparameter issue.
> 
> @Catchen98 Please check if this is the case for you and you only have to adjust the hyperparameters.

Thank you for your reply, I will try the method you said

**Comment by Leo63963** [comment]
Hi Tim, thanks for the reply.
I am sorry I did not make it clear. the "with my detection results" in my previous issue means that I rebuilt the Faster R-CNN network, instead of the default one you used in your code. And I did not use private detector means I still use the detections provided by the MOT Benchmark. Sorry for that.
I aggre with you that it is just a hyperparameter issue.

**Comment by timmeinhardt** [comment]
And you already apply NMS and some score thresholding in your Faster R-CNN code? If not the `nms_threshold to 1.0 and score for 0.0` setting will not filter out any detection and might give you inferior results.

**Comment by Leo63963** [comment]
Yes, when training the Faster R-CNN, the nms_thresh is 0.7, and score_thresh is 0.5. And change them when used in tracking.
