### ISSUE TITLE
Can't install lap, lapsolver requirements

### ISSUE THREAD

**Issue by mphillips-valleyit** [phil-bergmann/tracking_wo_bnw#105]
This is on RHEL 7.8.  `pip install lap` and lapsolver fails with a g++ compilation error as described in [this issue](https://github.com/gatagat/lap/issues/24).  Is there a replacement or workaround?

**Comment by timmeinhardt** [comment]
Did you try the things suggested in the issue you are referring to? Did you check whether you have indeed g++ installed on your machine.

**Comment by mphillips-valleyit** [comment]
Yes, not having g++ installed was the issue.
