### ISSUE TITLE
Can't run on gpu.

### ISSUE THREAD

**Issue by sense42** [phil-bergmann/tracking_wo_bnw#106]
I was not able to run the test_tracktor on my gpu.  

i have installed:
- cuda 9,2
- pytorch and torchvision with cudasupport

when running tet_tracktor my gpu usage is at near 0%.

**Comment by timmeinhardt** [comment]
Hello, the repository supports running on GPUs which is tested and working. This might be an issue with your local configuration. Please do some debugging on your side. Thank you!
