### ISSUE TITLE
About Resnet101

### ISSUE THREAD

**Issue by Huwenzjw** [phil-bergmann/tracking_wo_bnw#110]
For the process of Reid ,  you use the feature of resnet101 in the code. Have you pre-trained the Resnet101 on the MOT17Det?

**Comment by timmeinhardt** [comment]
The reID network is independent of the object detector and uses a ResNet50 for feature extraction. This ResNet is trained on three datasets, namely, Market1501, CUHK03 and MOT16. MOT16 and MOT17 use the same image data and only differ in the provided sets of public detections, i.e., yes the reID network was trained on MOT17Det.

**Comment by Huwenzjw** [comment]
Thanks very much.I understand it

**Comment by timmeinhardt** [comment]
Can we close this issue?

**Comment by Huwenzjw** [comment]
Yes,you can
