### ISSUE TITLE
How can i use the model after trainning a new one?

### ISSUE THREAD

**Issue by Eloi-14855** [phil-bergmann/tracking_wo_bnw#111]
Hi, ty for your wonderfull job, i trainned my own detection model, wtih a new dataset. after that i get the model on my gdrive, but im getting issues using that model, how can i do it? i just downloaded it and changed it on output\output\faster_rcnn_fpn_training_mot_17

**Comment by timmeinhardt** [comment]
Hi, I am not sure what your question is about? You start `test_tracktor.py` and adjust the `tracktor.obj_detect_model` arguements.

**Comment by Eloi-14855** [comment]
yes, i did that, but i got that error
![333](https://user-images.githubusercontent.com/60934194/101168789-db92e000-3633-11eb-95b6-51e704e2c587.PNG)
it seems like that new model is a zip? im asking after the train of the detectetor, the new model is a zip? is not totally equal to your model_epoch_27.model

**Comment by timmeinhardt** [comment]
What are the PyTorch versions of your Google Colab notebook and tracking_wo_bnw repo? There is [this](https://github.com/pytorch/pytorch/issues/43766) issue. Apparently new versions of PyTorch save a zip by default.

**Comment by Eloi-14855** [comment]
Migth be that, because,im actually using on my project the 1.3.1 version that requirements ask for, and the colab version is the newest (1.7.0) ty for that advice ,will try to change  the colab version. im new to google colab if u know how to make it use the 1.3.1 version i would apreciate, meanwhile i will try to make the change. really ty for your reply already

**Comment by timmeinhardt** [comment]
Yes, this might the issue and I am also not sure how to run it in google colab with different pytorch versions. But you can run the google colab notebook locally and train the model in your own python environment.

**Comment by Eloi-14855** [comment]
wonderful, just make it, ty for your advice. i will leave the answer to my issue of someone need it and we can close the issue.
I replaced the 
![1](https://user-images.githubusercontent.com/60934194/101192689-591a1880-3653-11eb-9c6e-d2050090b38d.JPG)
for the oldest pytorch version that i use on my project:
![2](https://user-images.githubusercontent.com/60934194/101192929-b615ce80-3653-11eb-9a58-0e4f24ca4d45.JPG)
you will provably get a Pillow version error, so u can create a new cell and force reinstall pillow, like this:
!pip install --upgrade --force-reinstall pillow
after that u will get the final trainned model file perfect to replace the original one
