### ISSUE TITLE
pip install requirements meets some errors

### ISSUE THREAD

**Issue by szh91** [phil-bergmann/tracking_wo_bnw#112]
hi, when i pip install tensorflow-gpu==1.1.0, it's error:" ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.1.0. ERROR: No matching distribution found for tensorflow-gpu==1.1.0

and what is the version of pytorch?

**Comment by timmeinhardt** [comment]
You can find all versions in the requirements.txt or README.md. Please make sure to work with the proper Python version as well.

**Comment by timmeinhardt** [comment]
Can we close this issue?
