### ISSUE TITLE
The new object detector

### ISSUE THREAD

**Issue by Leo63963** [phil-bergmann/tracking_wo_bnw#113]
Hi ! @timmeinhardt 
Really admire your work, thanks for sharing.
Just would like to know, what is the different of **object detector** used between Tracker++ and Tracker++v2? There is a huge increase in terms of MOTA and IDF1.
Many thanks

**Comment by timmeinhardt** [comment]
There is no conceptual difference. We just retrained it on a newer PyTorch version and achieved superior results.

**Comment by timmeinhardt** [comment]
Can we close this issue?

**Comment by Leo63963** [comment]
Yes, sure. 
Thank you very much.
Best
