### ISSUE TITLE
About the public data

### ISSUE THREAD

**Issue by Huwenzjw** [phil-bergmann/tracking_wo_bnw#114]
First one about the process that by reclassifying and regressing the given public detections with a private object detector, you use Faster R-CNN in the code.But , in public algorithm,you don’t use this process. Does the data in this paper use this process?    So I was very confused.
    Second one about the analysis for Robustness to detections. For the public , You use detector to predict the tracklet and kill some tracklets by the scores and initiate some tracklets by public detections. So I run the code and find a thing.In some frames, the algorithm will still have detections of history targets not provided by public detections.So,I wonder if it works well when it has a detection gap. Hence, are there some detection provided by tracking algorithm?
   I really appreciate it if you answer these questions.Thanks very much.

**Comment by timmeinhardt** [comment]
1. We do indeed reclassify and regress the given public detections. This can be found in our code:

https://github.com/phil-bergmann/tracking_wo_bnw/blob/ffee0b71e0ecdbe6e946a49f6ddbee412b46b261/src/tracktor/tracker.py#L266

2. The robustness experiments are conducted on public detections. However, the nature of our tracker allows it to fill gaps in the provided public detections. In other words, we merely use the public detections to initialise a track. Afterwards, the object detector applies regression and classification to follow the object over the course of the sequence without further filtering/influence from the public detections.
