### ISSUE TITLE
File not found output/fpn/res101/mot_2017_train/voc_init_iccv19/config.yaml

### ISSUE THREAD

**Issue by szh91** [phil-bergmann/tracking_wo_bnw#115]

**Comment by timmeinhardt** [comment]
Are you working on the old `iccv_19` branch? If so you need to download the corresponding model zip file. But I recommend to work with the main branch and its latest version.

**Comment by szh91** [comment]
yes,  I have successfully run,  by the way, If I want to use other reid model in your work, how i can do it

**Comment by timmeinhardt** [comment]
Depends on the other reid model and its structure. But you have to integrate it into the codebase.

**Comment by szh91** [comment]
ok, thank you very much!
