### ISSUE TITLE
 file path error

### ISSUE THREAD

**Issue by szh91** [phil-bergmann/tracking_wo_bnw#118]
hi, when I run the test_tracktor.py, it has an error:
![image](https://user-images.githubusercontent.com/30435832/104254800-92477300-54b2-11eb-97e5-4783df0ff68c.png)

Where do I modify the file path？

**Comment by timmeinhardt** [comment]
Currently the data directory is unfortunately hard coded (see `src/tracktor/config.py`). I am using system links from the `data` directory to where I store all the datasets.
