### ISSUE TITLE
how to test on MOT15 dataset?

### ISSUE THREAD

**Issue by szh91** [phil-bergmann/tracking_wo_bnw#119]

**Comment by timmeinhardt** [comment]
Please have a look at `src/tracktor/datasets/factory.py`. In there you can find all supported datasets and how to start them, e.g., `mot15_test` for the MOT15 test set.

**Comment by szh91** [comment]
yes, I modify the dataset mot17_train_FRCNN ---> mot15_train   in tracktor.py
and run the test_tracktor.py, it has an error:
![image](https://user-images.githubusercontent.com/30435832/104391362-b66e8700-557a-11eb-8681-e46ef20e9f0f.png)

**Comment by timmeinhardt** [comment]
Please double check if your data is at the correct place and fully downloaded etc. I just double checked and am not getting your error.
