### ISSUE TITLE
The results of MOT15

### ISSUE THREAD

**Issue by Leo63963** [phil-bergmann/tracking_wo_bnw#120]
Hi !
Have you trained on MOT15 train set before obtain the MOT15 results for test ?
Or just do the test with network trained on MOT17Det.
Thanks

**Comment by timmeinhardt** [comment]
We did not specifically train the Faster R-CNN on the MOT15 train set. The MOT15 ground truth is not very reliable and is missing some objects.

**Comment by Leo63963** [comment]
So you mean test with network trained on MOT17Det directly?
Thanks

**Comment by timmeinhardt** [comment]
Yes, exactly.

**Comment by Leo63963** [comment]
Thanks for your reply.
