### ISSUE TITLE
Issue by running train_reid.py

### ISSUE THREAD

**Issue by AvinWangZH** [phil-bergmann/tracking_wo_bnw#121]
When I was running train_reid.py, I got the following error:

tracking_wo_bnw/src/tracktor/datasets/mot_reid.py", line 26, in __init__
    super().__init__(seq_name, vis_threshold=vis_threshold)
TypeError: __init__() missing 1 required positional argument: 'mot_dir'

Is there any fix for the problem?

**Comment by g2ox** [comment]
I'm having the exact same problem..

**Comment by timmeinhardt** [comment]
I just pushed a fix to the issue. Sorry for the inconvenience!

**Comment by timmeinhardt** [comment]
Can we close this issue?
