### ISSUE TITLE
Wrong link to MOT17Det and a wrong definition in yaml file 

### ISSUE THREAD

**Issue by NormanBeta** [phil-bergmann/tracking_wo_bnw#123]
In the README.md, the link to MOT17Det is _https://motchallenge.net/data/MOT17Det.zip_ instead of _https://motchallenge.net/data/MOT17.zip_.

In  ./experiments/cfgs/tracktor.yaml and ./output/tracktor/MOT17/Tracktor++/sacred_config.yaml, the definition of warp_mode is MOTION_EUCLIDEAN/MOTION_AFFINE, but it makes an error about **NameError: name 'MOTION_EUCLIDEAN' is not defined**, when I run **python experiments/scripts/test_tracktor.py**. After setting  to cv2.MOTION_EUCLIDEAN, it works.

**Comment by timmeinhardt** [comment]
THank you for pointing out the wrong link in our README.md. However, the `test_tracktor.py` script should work with the `warp_mode= MOTION_EUCLIDEAN ` without the `cv2.`. We changed this lately and maybe you did not update your code? Please check if your code calls the following line:

https://github.com/phil-bergmann/tracking_wo_bnw/blob/11d5365f6b8976ff418422fd28d1a0605bbefe17/src/tracktor/tracker.py#L36

**Comment by timmeinhardt** [comment]
Can we close this issue?
