### ISSUE TITLE
About the backbone network

### ISSUE THREAD

**Issue by Leo63963** [phil-bergmann/tracking_wo_bnw#126]
Hi! @timmeinhardt 
The backbone network in code seems ResNet50, however, it is ResNet101 on the paper. 
So it is ResNet50, is it?
Thanks.

**Comment by timmeinhardt** [comment]
The results in the paper where achieved with the `iccv_19` branch which includes by default a ResNet101. However, the `Tracktor++v2` results on the official (leaderboard)[https://motchallenge.net/results/MOT17/] where produced with the `master` branch, i.e.,  a ResNet101.

**Comment by Leo63963** [comment]
OK, I see.
Better results of Tracktor++v2 are achieved with a smaller network ResNet50. It is really remarkable.
Thanks.
