### ISSUE TITLE
frame_split and overall metrics

### ISSUE THREAD

**Issue by ferumchrome** [phil-bergmann/tracking_wo_bnw#137]
Hello! How the metrics are calculated when the frame_split is not [0, 1]?

For example, if I set frame_split=[0, 0.25] then the tracking happens only on the first quarter of each sequence, right? How the overall metrics are then computed? What tracks are used in the sequence for the remaining frame_split=[0.25,1]? 

Thanks!

**Comment by ferumchrome** [comment]
@timmeinhardt Hmm. When I run tracktor on full MOT20_train the metrics are all ok, but if I run it with frame_split=[0.3, 0.6] then IDF is only around 3% and MOTA even becomes negative.. do you have any ideas why something like this happens?

**Comment by timmeinhardt** [comment]
I am not sure why this is the case. You could use the `write_images` argument to output qualitative results and see if the tracking or its evaluation fails.

**Comment by ferumchrome** [comment]
I plotted the sequences and I think the problem may be in how results are recorded.

Frame split works just fine when it's of the form [0, x]. However, if you specify the beginning of the split as non-zero, then the results are misaligned.

**Comment by timmeinhardt** [comment]
Yes, looking at the code this makes total sense. I pushed some changes that should fix the issue.
