### ISSUE TITLE
an intuitve definition of "oracle trackers"

### ISSUE THREAD

**Issue by rambleramble** [phil-bergmann/tracking_wo_bnw#14]
It seems the authors borrowed the term "oracle" from  its original definition in classical antiquity. However, it is pretty confusing when the term appearing first time in your paper's section  4.2 title.

could you provide an intuitive explanation of what is oracle trackers, perhaps focusing on what is the purpose of these oracle trackers.  It sounds to me an ablation study in a sense, but with more of foreseeing potential research direction. Correct me if it is a wrong understanding. Thanks in advance

**Comment by timmeinhardt** [comment]
Your understanding of the oracle trackers is correct. Since we are advertising Tracktor as a platform and an evolution of the classic tracking-by-detection paradigm we provided the oracle trackers as a guidance for the most potential future research directions.
