### ISSUE TITLE
How to predict a vedio or a list of images, is there an instruction? 

### ISSUE THREAD

**Issue by maxlchina** [phil-bergmann/tracking_wo_bnw#15]

**Comment by timmeinhardt** [comment]
There is currently no way to directly predict objects in a given video or list of images. You have to implement a corresponding dataset and data loader or bring the video in MOT 17 format and use the existing loader.

**Comment by maxlchina** [comment]
Thank you for your reply.

**Comment by timmeinhardt** [comment]
No worries. Can we close this issue?
