### ISSUE TITLE
'FileNotFoundError: [Errno 2] No such file or directory: '\data\\MOT17\\train\\MOT17-02.json''

### ISSUE THREAD

**Issue by RashoAli** [phil-bergmann/tracking_wo_bnw#153]
Hi,
At the step Training the re-identification model we ran:

python experiments/scripts/train_reid.py

i get the error : 'FileNotFoundError: [Errno 2] No such file or directory: '\data\\MOT17\\train\\MOT17-02.json''

i checked  2DMOT2015, MOT16, MOT17Det, MOT17, MOT20Det and MOT20 non of witch has .json file.
is there a step that i have to do bevor ruuning  train_reid.py?

**Comment by k-fujimt** [comment]
Hi @timmeinhardt , thanks for your great work.
 
When I run `reid_mot_to_coco_gt.py` as you suggested in this issue, I have the following error.
```
Processing sequence MOT17-02-DPM in dataset MOT17
Traceback (most recent call last):
  File "experiments/evaluation_tools/reid_mot_to_coco_gt_original.py", line 199, in <module>
    main()
  File "experiments/evaluation_tools/reid_mot_to_coco_gt_original.py", line 127, in main
    for row_i, row in enumerate(gt.astype(float))]
  File "experiments/evaluation_tools/reid_mot_to_coco_gt_original.py", line 127, in <listcomp>
    for row_i, row in enumerate(gt.astype(float))]
  File "experiments/evaluation_tools/reid_mot_to_coco_gt_original.py", line 64, in get_img_id
    return int(f"{dataset[3:5]}{seq.split('-')[-1]}{int(fname.split('.')[0]):06}")
ValueError: invalid literal for int() with base 10: '17DPM000001'
```
Is there any idea to fix this problem?

**Comment by timmeinhardt** [comment]
Just pushed a commit which should fix the issue.

**Comment by k-fujimt** [comment]
Thank you for your quick update!

**Comment by timmeinhardt** [comment]
Can we close this issue?

**Comment by RashoAli** [comment]
yes, thanks for the help
