### ISSUE TITLE
Tracktor precision

### ISSUE THREAD

**Issue by Tangzl7** [phil-bergmann/tracking_wo_bnw#156]
Tracktor can not reach the precision MOTA:61.5 which is mentioned in the paper. I set do_reid and do_align to false and I didn't change other option. The result is as follows:

                IDF1   IDP   IDR  Rcll  Prcn  GT  MT  PT  ML  FP    FN  IDs   FM  MOTA  MOTP IDt  IDa IDm
MOT17-02-FRCNN 43.0% 73.6% 30.4% 41.3% 99.8%  62   8  32  22  15 10916   65   65 40.8% 0.079   9   59   3
MOT17-04-FRCNN 70.0% 88.9% 57.7% 64.7% 99.8%  83  32  29  22  67 16775   23   29 64.5% 0.096   5   20   2
MOT17-05-FRCNN 57.0% 77.6% 45.0% 57.0% 98.3% 133  29  65  39  70  2975  161   70 53.7% 0.141  31  138   8
MOT17-09-FRCNN 57.9% 73.7% 47.7% 64.2% 99.1%  26  11  13   2  32  1907   31   31 63.0% 0.087   7   27   3
MOT17-10-FRCNN 44.1% 52.8% 37.9% 70.1% 97.8%  57  21  34   2 204  3843  414  225 65.3% 0.145 101  321   8
MOT17-11-FRCNN 61.0% 74.8% 51.5% 68.1% 99.0%  75  24  33  18  63  3007   65   34 66.8% 0.082   7   62   4
MOT17-13-FRCNN 54.3% 65.3% 46.5% 69.9% 98.1% 110  51  48  11 156  3502 1170  258 58.5% 0.134 176 1012  18
OVERALL        59.1% 77.0% 48.0% 61.8% 99.1% 546 176 254 116 607 42925 1929  712 59.5% 0.106 336 1639  46

MOTA is just 59.5

**Comment by timmeinhardt** [comment]
These are training set results. The model in the repository is less overfitted to those sequence, hence achieves smaller MOTA. Please check the `iccv_19' branch if you want to produce the exact results from the paper. But I recommend to work with the current master branch version as it achieves substantially better performance on test.

**Comment by Tangzl7** [comment]
Thank you for your reply. I will try it on 'iccv_19' branch.
