### ISSUE TITLE
Question: reproduce the model

### ISSUE THREAD

**Issue by Tangzl7** [phil-bergmann/tracking_wo_bnw#157]
Hello, I am reproducing tracktor(not ++), and I don't use the torchvision as my detector. My detector is frcnn-fpn(implement by mindspore) which is not exactly the same as the torchvision. And I train my detector in MOT17Det, which can only get 0.80 ap because  the prec is just 0.82. But my recall is 0.91, so I can change the parameter score_thresh(initially 0.05) to 0.9 to make my ap to 0.87.
I don't know if my detector is qualified, but I exactly train it for 30 epochs. And I use my detector for the tracktor. As a result, I just get 57.3 MOTA in MOT17-FRCNN.
1. Can I change the parameter score_thresh for a higher ap?
2. Should I keep training for more epochs so that my detector coulde get 0.9 ap?
3. If 0.9 ap is a important factor for tracktor's precision?

**Comment by timmeinhardt** [comment]
Hello, your object detector should be suitable for using it with Tracktor but training it properly  is something you have to do. For a high MOTA, the AP is not that important. If you evaluate your detection results with the official MOTChallenge devkit you will get the MODA (not MOTA) score. Tuning this score is a better indicator for high MOTA and yes the `detection_person_thresh` and `regression_person_thresh` are crucial for this.

**Comment by Tangzl7** [comment]
Thank you for your reply. I will keep trying.
