### ISSUE TITLE
Train reid and detector for custom objects /labels ( not people/cars)

### ISSUE THREAD

**Issue by whiteplatin** [phil-bergmann/tracking_wo_bnw#167]
Hi,

is there a guide on how to set up a custom dataset to train a reid model, including which annotation format to label the data as (e.g. Pacal, COCOjson etc.) ? Even a general tutorial would be fine, looking on the net , I was unable to find anything except for MOT and other similiar datasets.

The goal is to use this tracking algorithm for custom objects.

Thanks

**Comment by timmeinhardt** [comment]
We do not provide a detailed tutorial. But all the information can be found in the repo, e.g., for reid look at the `reid_mot_to_coco_gt.py` file.

**Comment by whiteplatin** [comment]
Hey thanks, can you give more details about the names of the annotation fomrat ?

Reid mot to coco ?

I mean I already have my dataset in coco format (but without the frame_id, which I guess is essential for reid training), Ive never heard of mot annotation, would this be the way to create it ,https://motchallenge.net/instructions/?

**Comment by whiteplatin** [comment]
I do not have `reid files` nor do I know what they are , if you have a link that would be great.

`reid_coco_to_coco_gt.py`does not seem to exist:
![image](https://user-images.githubusercontent.com/80218963/165106156-69504d4c-fae8-49fa-b72e-34fb366ffc40.png)

**Comment by timmeinhardt** [comment]
Sorry, the `reid_coco_to_coco_gt.py` file is not yet published. But you can find everything in the `reid_mot_to_coco_gt.py ` file. It shows what needs to be done to train reid. You can also look at this `https://pytorch.org/vision/stable/index.html`. Its the package we use for training reid.
