### ISSUE TITLE
how to reproduce the results of this repository on colab

### ISSUE THREAD

**Issue by sparshgarg23** [phil-bergmann/tracking_wo_bnw#168]
Hello,
I am highly interested in learning about MOT,and I thought that this repository would serve as an excellent starting point.
Since i don't have a gpu,I am running most of my deep learning experiments on colab.
So,when I tried following the installation instructions for this repository on colab,I ran into the following issues
```
while installing pytorch 1.7 and torchvision 0.8 i  ran into the following error
ERROR: Could not find a version that satisfies the requirement torchvision==0.8.0+cu110 
ERROR: No matching distribution found for torchvision==0.8.0+cu110
should i try installing torchvision 0.8.1
```
Secondly while executing pip requirements.txt
and error regarding matlab was thrown
```
ERROR: Could not find a version that satisfies the requirement matlabengineforpython===R2021a (from versions: none)
ERROR: No matching distribution found for matlabengineforpython===R2021a
```
Is matlab a hard requirement for running this code.I am assuming that matlab can't be run on colab.

Finally will this repository work fine with existing colab environment which comes with torch 1.11 +cu113?

**Comment by timmeinhardt** [comment]
Sorry but getting the repo running on colab is sth you have to figure out on your own as this might include running stuff with different package versions. The matlab package you might be able to skip but in the end this is all try and error to check what is possible on colab and what is not!

**Comment by sparshgarg23** [comment]
ok thanks .
