### ISSUE TITLE
Online or Offline method

### ISSUE THREAD

**Issue by andreaceruti** [phil-bergmann/tracking_wo_bnw#169]
I have seen many papers, sorry if my question sounds stupid but, Is this method an "online" mot method, right?
If i am not wrong you use only information from past frames to decide the current frame boxes, you do not use also future detections.
Correct me if I am missing something please

**Comment by timmeinhardt** [comment]
You are correct. This method is online and only uses information of past frames.

**Comment by andreaceruti** [comment]
@timmeinhardt thank you!
