### ISSUE TITLE
The evaluation results are different 

### ISSUE THREAD

**Issue by lirui111** [phil-bergmann/tracking_wo_bnw#17]
I have run test_tracktor.py twice on the same device and evaluated the results using MOTChallenge devkit . But the evaluation results are different，and  there is a gap of 4% on MOTA using the train dataset of MOT17. I am a beginner with multi-target tracking and I want to know why this phenomenon occurs.
Thank you.

**Comment by timmeinhardt** [comment]
Can you specify which configuration you were trying to run and which results from the paper you were trying to reproduce? And post the command you used for running `test_tracktor.py`. Thank you!

**Comment by timmeinhardt** [comment]
Can we close this issue?
