### ISSUE TITLE
Problems about MOTDT

### ISSUE THREAD

**Issue by Tclamber** [phil-bergmann/tracking_wo_bnw#19]
Thanks for your great work! May I ask  that have you run MOTDT code supported by its author ?  I found it claims that it's a reimplement version and  the code performance is quite lower than what papar and MOT Challenge shows.

**Comment by timmeinhardt** [comment]
I am not sure which results you are referring to. The detection results reported in Table 1 of the supplementary?

**Comment by Tclamber** [comment]
I refer the results about MOTDT on Table2. I run
its reimplement code and found that evaluation results are quite lower. I wonder whether your experiments about MOTDT shown on Figure2 and Figure3 are performed by the reimplement version code ？

**Comment by timmeinhardt** [comment]
Ah sorry, I confused MOTDT with the MOT detection challenge. No, we did not reimplement the MOTDT results but used their numbers from the official MOTChallenge [webpage](https://motchallenge.net/tracker/MOTDT17).

**Comment by Tclamber** [comment]
Thanks. I see. I am still interested in how you conduct the experiments shown on Figure 2 and  Figure 3.  Only use their evaluation numbers？

**Comment by timmeinhardt** [comment]
The MOTChallenge webpage allows to directly download the raw prediction data. We conducted our analysis on this data. See the raw data download button at the bottom of the [page](https://motchallenge.net/tracker/MOTDT17).

**Comment by timmeinhardt** [comment]
Can we close this issue?
