### ISSUE TITLE
Question about data

### ISSUE THREAD

**Issue by Bingobingo123** [phil-bergmann/tracking_wo_bnw#2]
Hello,

I have a question regarding the given dataset.

In step 4 it's asked to download the MOT Challenge dataset. There is a dataset called MOT16Labels. Although the name contains 16, but the folder in it contains actually the detection (DPM, FRCNN, SDP) from MOT17. Besides, according to MOTChallenge website, MOT16 only offers detection DPM.

I would like to ask what's the difference between the dataset MOT16Labels and MOT17Labels? Is this a mistake?

Thank you in advance

**Comment by timmeinhardt** [comment]
Please double check if you did not overwrite one set of detections with another. I just checked and the zip files contain the correct labels for MOT16 and MOT17. Make sure to unzip them with the given commands, e.g., `unzip -d MOT16Labels MOT16Labels.zip`, to create individual subfolders.

**Comment by Bingobingo123** [comment]
Sorry it was my mistake. Thank you very much for your rapid reply!
