### ISSUE TITLE
Which pytorch version should be used?

### ISSUE THREAD

**Issue by Midhilesh29** [phil-bergmann/tracking_wo_bnw#23]
If I uses pytorch 1.3 error occurs at compiling FasterRCNN as "ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")", but able to load weights FasterRCNN. 
On the other hand if I use pytorch 0.4 FasterRCNN is able to compile but weights are unable to load.

so which pytorch verison need to be used?

**Comment by timmeinhardt** [comment]
Please have a look at our README.md. It specifies the correct PyTorch version necessary to run this code.

**Comment by edithzeng** [comment]
I got the same error with CUDA 9.0 and torch==0.3.1 on Ubuntu 16.04.6.

**Comment by timmeinhardt** [comment]
Which error? The error during compilation or loading of the weights? For the latter, could you please describe in more detail what means "unable to load"?

**Comment by timmeinhardt** [comment]
This seems to be a problem of your PyTorch installation. Although `ncvv` might be linked to the correct CUDA version, PyTorch might not be able to find it and compiles with 8.0 instead of 9.0. What is the output of 'torch.version.cuda'?

**Comment by Midhilesh29** [comment]
```
torch.version.cuda
'8.0.61'
```
So, how to change this cuda version?. If my GPU 2080Ti is not compatible with CUDA 9.0, is there any way to run your code?

**Comment by timmeinhardt** [comment]
You could try running the code only on CPU. And for the PyTorch cuda version, please double check all the CUDA paths (`CUDA_HOME`, ` LD_LIBRARY_PATH`, `PATH`, etc.) before installing PyTorch.

**Comment by Midhilesh29** [comment]
Thank you for helping me!! I will check it.

**Comment by timmeinhardt** [comment]
Can we close this issue?

**Comment by Midhilesh29** [comment]
yes sure, I will close it

**Comment by nicolaerosia** [comment]
@Midhilesh29 I have a RTX 2070, did you found a workaround? I've opened a new issue which is basically a duplicate of this, #35 and there's also #16
