### ISSUE TITLE
How to use multi-gpus in this code

### ISSUE THREAD

**Issue by kellenf** [phil-bergmann/tracking_wo_bnw#25]
Thanks for your progress first! It's a new direction for MOT problem.I have run your code succcessfully but with a slow speed to run all MOT17 Dataset.Did you have try to use multi-gpus to run this code?

**Comment by timmeinhardt** [comment]
There is currently no explicit multi-gpu support. However, you can run each sequence separately and thereby run multiple sequence evaluations on multiple GPUs in parallel.

**Comment by timmeinhardt** [comment]
Can we close this issue?

**Comment by kaikaizhu** [comment]
@kellenf @timmeinhardt 
I'm sorry that there is a problem with my network here. I can't connect to Google drive. Can you send the required weight files to my email? Thank you very much. My email is kaikai_zhu1@163.com.
