### ISSUE TITLE
AttributeError: 'FPN' object has no attribute 'detect'

### ISSUE THREAD

**Issue by achalddave** [phil-bergmann/tracking_wo_bnw#27]
Thanks for this wonderful code base - it was refreshingly easy to set up due to the instructions. I'm running into one issue: I'm trying to run the provided detector (by setting `public_detections: False`), but when using the FPN backbone, I get the following error:

```
File "experiments/scripts/test_tracktor.py", line 123, in my_main
  tracker.step(frame)
File "src/tracktor/tracker.py", line 323, in step
  _, scores, bbox_pred, rois = self.obj_detect.detect()
```

I believe this is because `detect` is not defined in src/tracktor/fpn.py the way it is for src/tracktor/frcnn.py. Is this not supported right now, or am I just looking in the wrong place?

Thanks!

**Comment by timmeinhardt** [comment]
Yes indeed, currently this method is missing and the FPN detector can only be applied to public detections. However, it should be fairly easy to adapt the method from `src/tracktor/frcnn.py` for the FPN detector.

**Comment by timmeinhardt** [comment]
The newest version of Tracktor includes the necessary methods to run private detections.
