### ISSUE TITLE
 Required argument 'inputMask' (pos 6) not found

### ISSUE THREAD

**Issue by 121649982** [phil-bergmann/tracking_wo_bnw#28]
when Ｉ test ,Ｉget the error：Required argument 'inputMask' (pos 6) not found

**Comment by timmeinhardt** [comment]
Can please provide more infos on what you are trying to run and what the exact error message is?

**Comment by 121649982** [comment]
thank you for for your answer,I have solved it by replace opencv with a lower version(3.4)

**Comment by timmeinhardt** [comment]
Can we close this issue?

**Comment by 121649982** [comment]
> Can we close this issue?

sure
