### ISSUE TITLE
How to see the real-time effect

### ISSUE THREAD

**Issue by 121649982** [phil-bergmann/tracking_wo_bnw#29]
Is there a demo to  see the real-time effect in a video,please？

**Comment by timmeinhardt** [comment]
The Tracktor evaluation provides a `write_images` parameter to plot frames with bounding boxes. See the corresponding config file `experiments/cfgs/tracktor.yaml` which also includes a `ffmpeg` command to convert the frames to a video.

**Comment by 121649982** [comment]
thank you!

**Comment by 121649982** [comment]
> The Tracktor evaluation provides a `write_images` parameter to plot frames with bounding boxes. See the corresponding config file `experiments/cfgs/tracktor.yaml` which also includes a `ffmpeg` command to convert the frames to a video.

thank you!

**Comment by timmeinhardt** [comment]
Can we close this issue?

**Comment by 121649982** [comment]
> Can we close this issue?

yes
