### ISSUE TITLE
setup.py not found

### ISSUE THREAD

**Issue by ray114115** [phil-bergmann/tracking_wo_bnw#3]
When I type pip3 install -e src/frcnn(fpn). There's an error:
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /media/ray/Data/MOT/tracking_wo_bnw/src/frcnn

Is there setup.py file in fpn/ or frcnn/ ?

**Comment by timmeinhardt** [comment]
There should be `setup.py` files in `src/frcnn` and `src/fpn`. If the directories are empty you did not clone repository with `git clone --recurse-submodules https://github.com/phil-bergmann/tracking_wo_bnw`.

**Comment by ray114115** [comment]
oh, my git clone have some problem. Thanks a lot.
