### ISSUE TITLE
Executing faster RCNN for demo

### ISSUE THREAD

**Issue by Sentient07** [phil-bergmann/tracking_wo_bnw#30]
Hello,

Thank you for sharing your code, I was wondering if there is a way to visualize the results for FasterRCNN's efficacy on MoT using the code and the weights that you have provided. 

Your Readme.md file mentions we have to use `PyTorch 0.3` and `Cuda 9`. However, the entire FasterRCNN repo is built on `torchvision` which requires `Torch>1.0` , contradicting your Readme instructions. Is there a way to visualize FasterRCNN results from this repository? Could you please help me figure out how to?

Cheers,

**Comment by Sentient07** [comment]
I tried to install `torchvision`. However, I face the same error as mentioned [here](https://github.com/phil-bergmann/tracking_wo_bnw/issues/23).

**Comment by timmeinhardt** [comment]
If you follow the instructions there should be no version conflicts. `torchvision` already existed prior to PyTorch 1.0.

You can visualize the results with the `write_images` parameter. Check the config files for more details.

**Comment by timmeinhardt** [comment]
Can we close this issue?

**Comment by Sentient07** [comment]
Hello Tim, 

Sorry for my late reply. I was able to debug the problem and apparently it was the `requirements.txt` that ended up updating `torchvision` and pytorch. To fix this, I re-installed torchvision(as specified int he requirements file) after installing the specific version of Pytorch. 

I am not sure if this could be an error with python. However, I have written a DockerFile to install the whole package as a container, making it easier to switch environments. If you think this would be helpful, I can share the DockerFile :)

Cheers,

**Comment by timmeinhardt** [comment]
Thank you for your response. Providing Docker files is definitely the future. However, I do not want to provide something in the repository that I am not familiar with. In general, I think the setup of this codebase with a Python virtual environment should be doable. But thank you for your efforts!

**Comment by timmeinhardt** [comment]
Can we close this issue?

**Comment by Sentient07** [comment]
Hi Tim,

Sure, you can close the issue. I got quite occupied with other issues and didn't have time to share the Dockerfile. I hope to open a PR soon. :)
