### ISSUE TITLE
find a bug in motion model

### ISSUE THREAD

**Issue by withinnoitatpmet** [phil-bergmann/tracking_wo_bnw#32]

**Comment by withinnoitatpmet** [comment]
Hi,

I found a bug in using motion model. src/tracktor/tracker.py always update t.last_pos before applying motion model, the velocity is always 0.
Here is a easy fix:
`git diff src/tracktor/tracker.py
diff --git a/src/tracktor/tracker.py b/src/tracktor/tracker.py
index ed54d1b..d7a4fb5 100644
--- a/src/tracktor/tracker.py
+++ b/src/tracktor/tracker.py
@@ -34,7 +34,7 @@ class Tracker():
                self.reid_iou_threshold = tracker_cfg['reid_iou_threshold']
                self.do_align = tracker_cfg['do_align']
                self.motion_model = tracker_cfg['motion_model']
-
+               print('motion {}'.format(self.motion_model))
                self.warp_mode = eval(tracker_cfg['warp_mode'])
                self.number_of_iterations = tracker_cfg['number_of_iterations']
                self.termination_eps = tracker_cfg['termination_eps']
@@ -268,7 +268,6 @@ class Tracker():
                        cyp = (y2p + y1p)/2
                        wp = x2p - x1p
                        hp = y2p - y1p
-
                        # v = cp - cl, x_new = v + cp = 2cp - cl
                        cxp_new = 2*cxp - cxl
                        cyp_new = 2*cyp - cyl
@@ -306,7 +305,8 @@ class Tracker():
                containing the image information.
                """
                for t in self.tracks:
-                       t.last_pos = t.pos.clone()
+                       if len(t.last_pos.size()) == 0:
+                               t.last_pos = t.pos.clone()
 
                ###########################
                # Look for new detections #
@@ -353,6 +353,8 @@ class Tracker():
                        if self.motion_model:
                                self.motion()
                        #regress
+                       for t in self.tracks:
+                               t.last_pos = t.pos.clone()
                        person_scores = self.regress_tracks(blob)
 
                        if len(self.tracks):`

**Comment by timmeinhardt** [comment]
The current version of the code should resolve this bug already. But thank you for the hint!
