### ISSUE TITLE
Evaluation FPN detector

### ISSUE THREAD

**Issue by DYT-code** [phil-bergmann/tracking_wo_bnw#33]
Hello,
I have tested the provided object detector using the following code given in Readme to check the object detector:
python experiments/scripts/test_fpn.py voc_init_iccv19 --cuda --net res101 --dataset mot_2017_train --imdbval_name mot_2017_train --checkepoch 27

The weight I test is the weight you provide in your google drive, which is "res101/mot_2017_train/voc_init_iccv19/fpn_1_27.pth".
I haven't done any changes to the weight and the test code.

However, I can't get the same result as reported in your paper, which is 
![image](https://user-images.githubusercontent.com/46490590/69161470-813be580-0aeb-11ea-994c-7e75828974a4.png)
The result I got from the test code is:
AP: 0.7896991147961206 Prec: 0.8078499487666508 Rec: 0.9737321705601494 TP: 64649.0 FP: 15377.0
The result varies a lot and I am not sure if I have done anything wrong during the implementation. Could you please help? Thanks!

**Comment by timmeinhardt** [comment]
The results reported in this table are test set results which we obtained after submitting to the official MOT detection challenge.

**Comment by timmeinhardt** [comment]
Can we close this issue?
