### ISSUE TITLE
About Reid network

### ISSUE THREAD

**Issue by cosimo17** [phil-bergmann/tracking_wo_bnw#34]
Nice work!
I find that the reid network referd in your paper was trained on mot dataset.
Have you ever compared you reid network with other SOTA reid network which trained on large dataset?

**Comment by timmeinhardt** [comment]
We did not compare our reID methods with others. There are definitely better reID methods out there, we added this simple reID only to showcase the extensibility of Tracktor.

**Comment by cosimo17** [comment]
OK. I know. Thanks for your reply.
