### ISSUE TITLE
Which tensorflow version is required?

### ISSUE THREAD

**Issue by XiongDei** [phil-bergmann/tracking_wo_bnw#36]
The requirements text said the required the tensorflow version is 1.1.0, but it seems that tensorflow 1.1.0 is not compatible with cuda 9.0. I am confusing about the configuration.
Thanks.

**Comment by timmeinhardt** [comment]
In which sense is it not compatible? We only use `TensorFlow` for `Tensorboard`, i.e., no CUDA related functions are called.

**Comment by XiongDei** [comment]
Thanks for your reply. I get it.

**Comment by timmeinhardt** [comment]
Can we close this issue?
