### ISSUE TITLE
Use own or detections provided by mot for detection-part "offline"

### ISSUE THREAD

**Issue by AliRashidnejad** [phil-bergmann/tracking_wo_bnw#37]
hi, thanks for publishing this. 

how can one use offline detections instead of using the whole pipe-line ? I'm using this as a baseline for my master thesis and my other codes are working in Cuda10, would be great if I could use offline detections to focus on other functionalities.

**Comment by timmeinhardt** [comment]
What do you mean by offline detections? Our tracker is online and works with public or private detections. I am not familiar with the concept of "offline detections".

**Comment by AliRashidnejad** [comment]
sorry for ambiguous concept, I meant instead of detecting objects using Faster-RCNN in each frame, loading the detections (as you said) and let tracktor do its tracking based on this info. I guess your repo is most probabely designed in this way but following your instructions for generating demo with "test_tracktor.py" I had to install also a the pipeline for detection (cuda 9.0, torch 0.3.1 etc). how could I run the code using these public/private detections you said?

**Comment by timmeinhardt** [comment]
What you described is just what Tracktor does. We are loading the provided public detections and then Tracktor applies its regression to generate frame to frame tracks. 

The current version of Tracktor supports newer version of CUDA and PyTorch 1.3. Maybe this already resolves your issues.

**Comment by timmeinhardt** [comment]
Can we close this issue?
