### ISSUE TITLE
Readme link not working

### ISSUE THREAD

**Issue by ringochuchudull** [phil-bergmann/tracking_wo_bnw#38]
Hi,

Your readme section:

```
Download object detector and re-identifiaction Siamese network weights and MOTChallenge result files for ICCV 2019:

Download zip file from here.

Extract in output directory.
```

The link that contains the zip file is not working... Could you correct that please?

Yours sincerely

**Comment by timmeinhardt** [comment]
Sorry, I reuploaded the files yesterday and update with the wrong link. Now it should work again.

**Comment by timmeinhardt** [comment]
Can we close this issue?
