### ISSUE TITLE
Dataset  issue

### ISSUE THREAD

**Issue by ks322181** [phil-bergmann/tracking_wo_bnw#39]
I am trying for my own dataset. but it is asking for gt and det files. But according to the base paper ,algorithm will be using faster RCNN for object detection. Then y it is asking for ground truth and detection file. Is it compulsory to have the two files in dataset.

Thanks in Advance.

**Comment by timmeinhardt** [comment]
Tracktor actually works with public and private detections. If you do not have detections or ground truth files for your own dataset you might have to adjust the code accordingly.

**Comment by timmeinhardt** [comment]
Can we close this issue?

**Comment by ks322181** [comment]
yes sure. Thanks for the help.
