### ISSUE TITLE
test on my own dataset

### ISSUE THREAD

**Issue by ray114115** [phil-bergmann/tracking_wo_bnw#4]
Hi,
I want to train on my dataset, my data set is MOT17 format. But the target is car, not person. So I think I need to retrain object detector and re-identifaction Siamese network, is that right?

I have not trained the object detector yet.
When I training re-identifaction Siamese network, it has error message:
  File "experiments/scripts/train_siamese.py", line 86, in my_main
    max_epochs = 25000 // len(db_train.dataset) + 1 if 25000%len(db_train.dataset) else 25000 // len(db_train.dataset)
ZeroDivisionError: integer division or modulo by zero

Which files are needed to change the name from "MOT17" to "Car" ?

**Comment by timmeinhardt** [comment]
Yes, you have to retrain the object detector and the reID Siamese network. 

The error originates from the `len()` operation on your dataset which returns zero. This operation should return the number of images in your dataset. Please check the `MOT17_Sequence` class in `src/tracktor/datasets/mot_sequence.py` and debug your dataset.

If your data format is just as MOT17 but with cars instead of persons you don`t have to change anything to "Car". But again, make yourself familiar with the `MOT17_Sequence`.

**Comment by ray114115** [comment]
I can run Tracktor by executing:
python experiments/scripts/test_tracktor.py

So, I think the file "train_siamese.py" did not catch the path correctly.
I renamed the train_folders from "MOT17-XX" to "CAR-XX" in the file "mot_siamese_wrapper.py", but it still not working. Will there be other similar files that need to be changed? I will try hard again.

Thank you for reply.

**Comment by timmeinhardt** [comment]
I do not know the folder and file structure of your dataset to give you definite answers. The Siamese training works for the MOT17 dataset. If your dataset differs somehow it might not work. I am sorry but you have to debug and find the issues in the respective files. 

If you find a general error or rewrite the code to make it more suitable for new datasets we are happy to receive a pull request.

**Comment by ray114115** [comment]
Hi, I want to train object detector, but it connot run on this repository(file structure is wrong). How can I train the detector? different repository?

**Comment by ray114115** [comment]
Hi, If I want to train object detector, I need to convert my dataset format from MOT17 to VOC, is that right? or I don't need to do that?
How about training the re-identifaction Siamese network? What kind of format should be? MOT17 or VOC format?
