### ISSUE TITLE
Problem with requirements.txt

### ISSUE THREAD

**Issue by Vijaya-25** [phil-bergmann/tracking_wo_bnw#41]
Line no 83 in requirements.txt file is throwing an error while running the command pip3 install -r requirements.txt

**Comment by ringochuchudull** [comment]
Hi,

I have encountered the same problem... The error comes from the below line from requirement.txt

```
-e git+git@github.com:phil-bergmann/tracking_wo_BnW@30b89259243251c816e45ef70d13dd3df49b7b48#egg=tracktor
```

It says permission denied with no access right.

**Comment by timmeinhardt** [comment]
Hello, sorry for the inconvenience, I removed this line from the `requirements.txt`. Now it should work

**Comment by tiberium24** [comment]
About the part, python 3.7 virtual environment, I am having trouble when I do that with the dependencies.. Can you specifically say how you do that or at least provide a Dockerfile for the whole repo?

**Comment by Vijaya-25** [comment]
Jupyter-console 6.0.0 requires prompt-toolkit above 2.0.0. so i modified prompt toolkit to version above 2.0.0 but it is creating an issue for ipython. Ipython requires prompt-toolkit version below 2.0.0 

requirement.txt  file

**Comment by timmeinhardt** [comment]
@tiberium24 We do not have Docker files for the repo. I work with [pyenv](https://github.com/pyenv/pyenv) for the different Python version and they have a `virtualenv` extension. Pleas make youself familiar with the Python versioning and the different tools as this is beyond the scope of this repository.

@Vijaya-25 We never encountered any version conflicts when students followed the instructions in the README. Are u working in a virtual environment?

**Comment by timmeinhardt** [comment]
Can we close this issue?
