### ISSUE TITLE
Train and Test Object Detector

### ISSUE THREAD

**Issue by ks322181** [phil-bergmann/tracking_wo_bnw#42]
Object Detector is trained and tested on google colab notebook. Can we do it locally on machine?

**Comment by timmeinhardt** [comment]
You can run Google Colab notebooks with a local Jupyter notebook server. There are plenty of tutorials online.

**Comment by tangjiasheng** [comment]
> You can run Google Colab notebooks with a local Jupyter notebook server. There are plenty of tutorials online.

Can you provide some numbers of training the detector? Such as `"AP: {ap} Prec: {prec} Rec: {rec} TP: {tp} FP: {fp}"` at the end oof training. Because I have troubles on evaluating it with MODA.

**Comment by timmeinhardt** [comment]
Please have a look at the README. We provide the object detections metrics on MOT17Det challenge.
