### ISSUE TITLE
running the default configuration fails

### ISSUE THREAD

**Issue by username72764274** [phil-bergmann/tracking_wo_bnw#43]
I followed the described installation steps in the readme file.
Running `python experiments/scripts/test_tracktor.py` fails with the following error:

> python experiments/scripts/test_tracktor.py 
WARNING - test_tracktor - No observers have been added to this run
INFO - test_tracktor - Running command 'main'
INFO - test_tracktor - Started
ERROR - test_tracktor - Failed after 0:00:00!
Usage:
  test_tracktor.py [(with UPDATE...)] [options]
  test_tracktor.py help [COMMAND]
  test_tracktor.py (-h | --help)
  test_tracktor.py COMMAND [(with UPDATE...)] [options]
sacred.utils.MissingConfigError: main is missing value(s): ['reid']

Is it necessary to add an additional reid config?

**Comment by timmeinhardt** [comment]
This is an error in the `output/tracktor/reid/res50-mot17-batch_hard/sacred_config.yaml`. I reuploaded the correct file, but you can just replace `siamese` with `reid` in the file and it should work.

**Comment by username72764274** [comment]
Thanks. I downloaded the new output files and the command is now working.
