### ISSUE TITLE
RunTimeError

### ISSUE THREAD

**Issue by ks322181** [phil-bergmann/tracking_wo_bnw#45]
Runtimerror: Attempting to deserialize objects on CUDA device but torch.cuda.is_available is False. If you are running on a cpu only machine . Please use torch.load with map_location=torch.device('cpu') to map your storage to cpu

I think there is a problem with torch and torchvision version

Can anyone help me?
Thanks in Advance.

**Comment by yexing99** [comment]
I got the same error but fixed it by obj_detect_state_dict = torch.load(_config['tracktor']['obj_detect_model'],map_location=torch.device('cpu'))

**Comment by timmeinhardt** [comment]
This is indeed an issue of running the code on CPU and our models being trained on GPU. I just pushed a change which should resolve this issue and is similar to @yexing99 solution.

**Comment by timmeinhardt** [comment]
Can we close this issue?

**Comment by ks322181** [comment]
I am working on GPU system. Where i have cuda version 8. But still i am facing the same issue. Is it compatible with cuda 8. If not can you specific which cuda version it will support.

**Comment by timmeinhardt** [comment]
If you look at the `requirements.txt` you can see that our code currently runs with PyTorch 1.3 which in turn is [compatible](https://pytorch.org/) with CUDA 9.2 and 10.1.

**Comment by ks322181** [comment]
Thanks i will check with higher version of cuda.
