### ISSUE TITLE
Detection and ReID weight for CVPR19 challenge

### ISSUE THREAD

**Issue by DYT-code** [phil-bergmann/tracking_wo_bnw#47]
Hello,

thanks for your great work. 

For the MOT challenge CVPR2019 your tracktor also gets nice result. Could you please also share the weight of detection and reid network of the TracktorCV?

Thank you very much!

**Comment by timmeinhardt** [comment]
We are working on this and will release them probably next year.

**Comment by yjmlaile** [comment]
hello
tanks for your sharing of code.
I use the tracktor with weight training on MOT17 to  conduct experiment on MOT20 and achieve a bad results, after trained on MOT20, no substantial improvement can be achieve. I think it is due to the chosen of hyper-parameter e.g. some threshold, so I just hope you could provide those hyper-parameter used in MOT challenge CVPR2019.

**Comment by timmeinhardt** [comment]
How are your object detection metrics after training on MOT20? First you should check if the Faster RCNN was properly trained.

**Comment by yjmlaile** [comment]
@timmeinhardt I conduct two experiments, one use the given weight trained on MOT17 detection dataset, the other is trained on MOT20 dataset. The both results are worse than the shown one, of course the former is the worst. So i think it due to the chosen of hyper-parameters.

**Comment by timmeinhardt** [comment]
Yes, the fact that after training on MOT20 the results got better shows that the training did something. But it does not show that the object detector was actually trained properly. Please make sure that your detector is actually trained properly. For example by doing a cross validation on the training set.

**Comment by yjmlaile** [comment]
@timmeinhardt After training the object detector on MOT20 dataset, I get better test results:MOTA:50.8% that are still worse than your public results. I want know If the the hyper-parameters used on MOT20 dataset are same with those in MOT17 dataset and the ReID network are trained on MOT20 dataset.

**Comment by timmeinhardt** [comment]
Yes, you get better results on the tracking challenge. However, it is not clear if this is the optimal performance. One possibility is the detection performance of the object detector. Please check if it is trained successfully, e.g., by submitting to test or doing a cross validation. Only after you verified that the object detection performance is not the issue you should look at other hyperparameters. We achieved our CVPR 19 results with default hyperparameters.

**Comment by yjmlaile** [comment]
@timmeinhardt Thanks, do you mean the public results are obtain with using [this](https://colab.research.google.com/drive/1_arNo-81SnqfbdtAhb3TBSU5H0JXQ0_1) for training on MOT20 dataset and with default hyperparameters?

**Comment by timmeinhardt** [comment]
Not exactly with the code in the notebook but an analogous training procedure. It should be noted, that our CVPR 2019 results where obtained with the old version of this repo. This new version should receive even superior performance.

**Comment by yjmlaile** [comment]
@timmeinhardt thanks for your patient reply.

**Comment by timmeinhardt** [comment]
The repository now contains the MOT20 results and model files. I will close this issue.
