### ISSUE TITLE
how about the runtime speed 

### ISSUE THREAD

**Issue by sunbinbin1991** [phil-bergmann/tracking_wo_bnw#48]
Thanks for your kind work，here is some question 
* 1: how about the runtime speed ?
* 2:  if i use it in mobile device, is it convenience for transplant?
* 3: also I have a detector (yolo3 )already, need i retrain a new network for regress and classify?

**Comment by timmeinhardt** [comment]
1. Please look at the paper and the official MOTChallenge webpage for runtime information.
2. Porting this codebase to mobile should be possible but I am not experienced in that regard.
3. Please make yourself familiar with Tracktor and your object detector to estimate if they are compatible. For optimal performance on MOT you probably want to retrain/finetune it.

**Comment by sunbinbin1991** [comment]
Thanks for your kind apply, just follow  your word, I find runtime information
