### ISSUE TITLE
Can't download weight file

### ISSUE THREAD

**Issue by agirbau** [phil-bergmann/tracking_wo_bnw#5]
Hello! 
I'm trying to download the weight files and I get this message:
"ERROR 400: Bad Request"

Could you please check if the weightfile is correctly uploaded? Thank you!

**Comment by timmeinhardt** [comment]
Does the link redirect you to Google Drive? I just checked and downloaded the zip file.

**Comment by agirbau** [comment]
Hello, 
it seems it was my computer doing weird stuff, sorry for the inconvenience and thank you!
