### ISSUE TITLE
About the results in papers

### ISSUE THREAD

**Issue by Huwenzjw** [phil-bergmann/tracking_wo_bnw#53]
hello，I just  want  to know the results in papers that you record the boxes .The boxes are the boxes which are provided by MOTchanllege or the FPN .In your code ,"	self.results[t.id][self.im_index] = np.concatenate([t.pos[0].cpu().numpy(), np.array([t.score])])"  ,the boxes are provided by FPN.How about the boxes in papers？Thanks very much

**Comment by timmeinhardt** [comment]
Sorry, but I am not sure if I understand your question correctly. Our bounding box predictions are the result of regressing the public detection boxes (provided by the MOTChallenge) with the regressor of the FPN. In the public setting we are never using the FPN to provide additional detections.

**Comment by timmeinhardt** [comment]
Can we close this issue?
