### ISSUE TITLE
How to trian feaster CNN

### ISSUE THREAD

**Issue by jinyl777** [phil-bergmann/tracking_wo_bnw#54]
how down the code to trian it
In your goegle i can not find the engine and do not understand  this code "from engine import train_one_epoch, evaluate"
I want to train it in my computer how can i do it

**Comment by timmeinhardt** [comment]
The `from engine import train_one_epoch, evaluate` import is from torchvision. Please have a detailed look at the Google Colab notebook. We clone the `torchvision` repository into the Google Colab workspace and then import directly from the folders.

**Comment by jinyl777** [comment]
thanks very match
