### ISSUE TITLE
unable to regenerate the results

### ISSUE THREAD

**Issue by sainathreddyb** [phil-bergmann/tracking_wo_bnw#56]
when i am trying to run the model it is saying zero tracks found, i followed the steps mentioned in the reame and tried running for mot17_train_frcnn dataset i.e default version in yaml.
can someone please help me on this issue

**Comment by timmeinhardt** [comment]
If I remember correctly, this can happen if the data is not in the correct folders. Maybe double check if the data is loaded and the paths are correct.

**Comment by sainathreddyb** [comment]
i can see the image information in the blob, secondly i have placed model files as said in the readme. 
in the output folder i am unable to find where i am going wrong. and i changes factory.py file few lines
before: 
 f'mot17_{split}_{dets}'
after:
'mot17_'+split+'_'+dets

as it was throwing syntax error what is this f in front of a string.
may be i am doing something wrong or misunderstood this notation can u help me in rerunning it correctly.

**Comment by timmeinhardt** [comment]
The code before should be `f'mot17_{split}_{dets}'` and this is correct syntax. Which Python version are you using?

**Comment by sainathreddyb** [comment]
version 3.5

**Comment by timmeinhardt** [comment]
Our code runs with Python version 3.7. And f-strings were introduced with 3.6 (https://realpython.com/python-f-strings/). This might be the problem.

**Comment by sainathreddyb** [comment]
now after changing to python 3.7 i got this error-
RuntimeError: The expanded size of the tensor (1920) must match the existing size (1333) at non-singleton dimension 2.  Target sizes: [3, 1080, 1920].  Tensor sizes: [3, 749, 1333]

**Comment by timmeinhardt** [comment]
I have not seen this error before but this should be debugable. Where in the code does the error occur?

**Comment by sainathreddyb** [comment]
s/scripts/test_tracktor.py
WARNING - test_tracktor - No observers have been added to this run
INFO - test_tracktor - Running command 'main'
INFO - test_tracktor - Started
Configuration (modified, added, typechanged, doc):
  seed = 453695
  reid:
    db_train = 'train'
    db_val = False
    desription = 'all'
    lr_scheduler = True
    max_epochs = 69
    module_name = 'reid'
    name = 'res50-mot17-batch_hard'
    seed = 12345
    cnn:
      output_dim = 128
    dataloader:
      K = 4
      P = 18
      crop_H = 256
      crop_W = 128
      max_per_person = 1000
      normalize_mean = [0.485, 0.456, 0.406]
      normalize_std = [0.229, 0.224, 0.225]
      transform = 'random'
      vis_threshold = 0.3
    model_args:
      loss = 'batch_hard'
      margin = 0.2
      prec_at_k = 3
    solver:
      optim = 'Adam'
      optim_args:
        lr = 0.0003
        weight_decay = 0.0
  tracktor:
    dataset = 'mot17_train_FRCNN17'
    desription = None
    frame_split = [0.0, 1.0]
    interpolate = False
    module_name = 'MOT17'
    name = 'Tracktor++'
    network = 'fpn'
    obj_detect_model = 'output/faster_rcnn_fpn_training_mot_17/model_epoch_27.model'
    reid_config = 'output/tracktor/reid/res50-mot17-batch_hard/sacred_config.yaml'
    reid_weights = 'output/tracktor/reid/res50-mot17-batch_hard/ResNet_iter_25245.pth'
    seed = 12345
    write_images = False
    tracker:
      detection_nms_thresh = 0.3
      detection_person_thresh = 0.5
      do_align = True
      do_reid = True
      inactive_patience = 10
      max_features_num = 10
      number_of_iterations = 100
      public_detections = True
      regression_nms_thresh = 0.6
      regression_person_thresh = 0.5
      reid_iou_threshold = 0.2
      reid_sim_threshold = 2.0
      termination_eps = 1e-05
      warp_mode = 'cv2.MOTION_EUCLIDEAN'
      motion_model:
        center_only = True
        enabled = False
        n_steps = 1
INFO - main - Initializing object detector.
INFO - main - Tracking: MOT17-02-FRCNN
  0%|                                                   | 0/600 [00:00<?, ?it/s]
ERROR - test_tracktor - Failed after 0:00:05!
Traceback (most recent calls WITHOUT Sacred internals):
  File "experiments/scripts/test_tracktor.py", line 93, in main
    tracker.step(frame)
  File "/home/santoshv/sainath/tracking_wo_bnw/src/tracktor/tracker.py", line 264, in step
    boxes, scores = self.obj_detect.predict_boxes(blob['img'], dets)
  File "/home/santoshv/sainath/tracking_wo_bnw/src/tracktor/frcnn_fpn.py", line 30, in predict_boxes
    images, targets = self.transform(images, targets)
  File "/home/santoshv/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/santoshv/.local/lib/python3.7/site-packages/torchvision/models/detection/transform.py", line 41, in forward
    images[i] = image
RuntimeError: The expanded size of the tensor (1920) must match the existing size (1333) at non-singleton dimension 2.  Target sizes: [3, 1080, 1920].  Tensor sizes: [3, 749, 1333]

this is the trace

**Comment by timmeinhardt** [comment]
Do you have the correct `torchvision` and `torch` version? As in the `requirements.txt`?

**Comment by sainathreddyb** [comment]
no i have pytorch 1.1.0 and torchvision 0.3 because of gpu supports only cuda 9.0 i had to use that version is the problem because of pytorch version??

**Comment by timmeinhardt** [comment]
Both introduce breaking changes all the time. Please follow the README.md and install the correct versions. The error above happens in a torchvision function which makes the version missmatch a very good candidate for the reason of the error.

**Comment by timmeinhardt** [comment]
Did you get it running? Can we close this issue?

**Comment by sainathreddyb** [comment]
you can close the issue. I dont have supporting hardware to run on cuda 10 so i cant install latest version of pytorch or torchvision. Please let me know if there is any workaround to run it on pytorch 1.1 and cuda 9.0.

**Comment by timmeinhardt** [comment]
You can try to run it on the maximum versions that your system allwos. with the correct `torchvision` version and see if it works, or run it on CPU. Sorry for the inconvenience.
