### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by NohYoon** [phil-bergmann/tracking_wo_bnw#59]
When I run test_trackor.py, I got the error message below.

RuntimeError: The expanded size of the tensor (1920) must match the existing size (1333) at non-singleton dimension 2.  Target sizes: [3, 1080, 1920].  Tensor sizes: [3, 749, 1333]

Is it about the torch version?

**Comment by timmeinhardt** [comment]
This doesn't look like a version problem. But you should double check if you have the correct versions. Where in the codebase does this error occur?

**Comment by NohYoon** [comment]
I ran the code by the instruction. I didn't change any of the source code.
Here is the full version of the error.


==================
INFO - main - Initializing object detector.
INFO - main - Tracking: MOT17-02-FRCNN
  0%|                                                                                          | 0/600 [00:00<?, ?it/s]
ERROR - test_tracktor - Failed after 0:00:15!
Traceback (most recent calls WITHOUT Sacred internals):
  File "./experiments/scripts/test_tracktor.py", line 93, in main
    tracker.step(frame)
  File "d:\dropbox\돼지\tracking_without_bells_and_whitles\src\tracktor\tracker.py", line 264, in step
    boxes, scores = self.obj_detect.predict_boxes(blob['img'], dets)
  File "d:\dropbox\돼지\tracking_without_bells_and_whitles\src\tracktor\frcnn_fpn.py", line 30, in predict_boxes
    images, targets = self.transform(images, targets)
  File "C:\Users\nohyoon seong\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\nohyoon seong\Anaconda3\envs\pytorch\lib\site-packages\torchvision\models\detection\transform.py", line 41, in forward
    images[i] = image
RuntimeError: The expanded size of the tensor (1920) must match the existing size (1333) at non-singleton dimension 2.  Target sizes: [3, 1080, 1920].  Tensor sizes: [3, 749, 1333]
===================

**Comment by timmeinhardt** [comment]
What is your `torchvision` version?

**Comment by NohYoon** [comment]
Here is my torchvision version.

>>> import torchvision
>>> torchvision.__version__
'0.3.0'

**Comment by timmeinhardt** [comment]
This is indeed not the same as necessary for this repository. Please double check all your versions and follow the instructions in the README.md.

**Comment by timmeinhardt** [comment]
Can we close this issue?

**Comment by WangHonglie** [comment]
I met the same problem with yours, did you solve it?.

> When I run test_trackor.py, I got the error message below.
> 
> RuntimeError: The expanded size of the tensor (1920) must match the existing size (1333) at non-singleton dimension 2. Target sizes: [3, 1080, 1920]. Tensor sizes: [3, 749, 1333]
> 
> Is it about the torch version?

**Comment by Marshall2M** [comment]
> I met the same problem with yours, did you solve it?.
> 
> > When I run test_trackor.py, I got the error message below.
> > RuntimeError: The expanded size of the tensor (1920) must match the existing size (1333) at non-singleton dimension 2. Target sizes: [3, 1080, 1920]. Tensor sizes: [3, 749, 1333]
> > Is it about the torch version?

Same problem here, did you solve it? My torchvision is 0.3.0 because I use CUDA9.0. torchvision 0.4.2 and CUDA10 is required, maybe that's the reason?

**Comment by timmeinhardt** [comment]
Yes, this is a version issue.

**Comment by Marshall2M** [comment]
> Yes, this is a version issue.

thx!
