### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by nightmaredimple** [phil-bergmann/tracking_wo_bnw#63]
Before reading your code, I have already implemented your paper on my own, which can reach 57.79 MOTA on MOT17. Besides, I have adopted some improvements to Tracktor++. Now the results can reach 60+MOTA on MOT17 with 7\~10FPS. If luckily, the code will be released upon acceptance of the paper which is submitted to ECCV20'. And I'm going to graduate with a master's degree this June. Thanks~

**Comment by timmeinhardt** [comment]
Thank you for the kind of words. We hope our paper and this codebase inspires many more follow-up papers and methods improving on the Tracktor baseline. Good luck with your submission!

**Comment by bluesky314** [comment]
@nightmaredimple Can you share your improvements? Has your paper been accepted?
