### ISSUE TITLE
Test Custom Dataset

### ISSUE THREAD

**Issue by Gazi13** [phil-bergmann/tracking_wo_bnw#66]
Hi,

I want to see the result of this method on my dataset. I looked the other issues but i could not understand what should i do for this.
How should be the format of the dataset ?
Where should i change in the code for customize ? 
briefly...
What is the best way for unsderstranding what happening here. I know it's a very general question but i'll be glad if you can help me

**Comment by young-yangb** [comment]
I have the same question...and don't know what should I do?

**Comment by timmeinhardt** [comment]
There are multiple issues on this topic, e.g., https://github.com/phil-bergmann/tracking_wo_bnw/issues/4. Please make yourself familiar with the codebase and PyTorch in general. Adding your own dataset is analogous to any PyTorch codebase and includes the implementation of your own dataset class.
