### ISSUE TITLE
Error during installing requirements (matplotlib==3.1.1)

### ISSUE THREAD

**Issue by imchwan** [phil-bergmann/tracking_wo_bnw#67]
Dear @phil-bergmann, @timmeinhardt,
First of all, thank you for the great work.

I was trying to follow your step, and tried to install the requirements.
And it looks like matplotlib==3.1.1 is not supported for pip3 (see below error message)
**Is it ok to install matplolib==3.0.3 (it looks like it is the latest version)?**

> ERROR: Could not find a version that satisfies the requirement matplotlib==3.1.1 (from -r requirements.txt (line 37)) (from versions: 0.86, 0.86.1, 0.86.2, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1rc1, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc1, 2.2.0, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 3.0.0rc2, 3.0.0, 3.0.1, 3.0.2, 3.0.3)
> ERROR: No matching distribution found for matplotlib==3.1.1 (from -r requirements.txt (line 37))

Added)
**Is it ok to install pandas==0.24.2 (it looks like it is the latest version)?**
> ERROR: Could not find a version that satisfies the requirement pandas==0.25.3 (from -r requirements.txt (line 50)) (from versions: 0.1, 0.2b0, 0.2b1, 0.2, 0.3.0b0, 0.3.0b2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0rc1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0rc1, 0.8.0rc2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0rc1, 0.19.0, 0.19.1, 0.19.2, 0.20.0rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0rc1, 0.21.0, 0.21.1, 0.22.0, 0.23.0rc2, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0rc1, 0.24.0, 0.24.1, 0.24.2)
> ERROR: No matching distribution found for pandas==0.25.3 (from -r requirements.txt (line 50))

**Comment by timmeinhardt** [comment]
Are you using Python 3.7 or an earlier version?

**Comment by timmeinhardt** [comment]
Can we close this issue?
