### ISSUE TITLE
How to use with pytorch 1.0 for compatible with CUDA 10?

### ISSUE THREAD

**Issue by sangnguyenz** [phil-bergmann/tracking_wo_bnw#7]
Is is possible to train faster-rcnn with pytorch 1.0 in this project?
Thank you.

**Comment by timmeinhardt** [comment]
Unfortunately the underlying faster-rcnn repository does not work with PyTorch 1.0. However, the most [recent version of torchvision](https://pytorch.org/blog/torchvision03/) provides Faster R-CNN out of the box and it should be quite easy to use our Tracktor code with that version of a Faster R-CNN. This would definitely be a contribution that we are happy to integrate into our repository.

**Comment by sangnguyenz** [comment]
> Unfortunately the underlying faster-rcnn repository does not work with PyTorch 1.0. However, the most [recent version of torchvision](https://pytorch.org/blog/torchvision03/) provides Faster R-CNN out of the box and it should be quite easy to use our Tracktor code with that version of a Faster R-CNN. This would definitely be a contribution that we are happy to integrate into our repository.

Thank you for your reply. I've done taking boxes and classes from FRCNN pre-trained model from PyTorch as you said. Next, Where can I take the code for integrating the detector and tracktor? Do I need to modify the tracktor evaluation for demo code?

Thank you

**Comment by timmeinhardt** [comment]
You would have to modify multiple files. Definitely `experiments/scripts/test_tracktor.py` and `src/tracktor/tracker.py`. It is definitely possible to switch out the underlying Faster-RCNN implementation but there is probably some work involved.

**Comment by sangnguyenz** [comment]
> You would have to modify multiple files. Definitely `experiments/scripts/test_tracktor.py` and `src/tracktor/tracker.py`. It is definitely possible to switch out the underlying Faster-RCNN implementation but there is probably some work involved.

Excuse me, Can you help me to explain the differences between Tracktor and Oracle Tracktor?
Thank you in advance.

**Comment by timmeinhardt** [comment]
Please have a look at Section 4.2 of our [paper](https://arxiv.org/abs/1903.05625). There we explain purpose of our oracle trackers and their distinctions.

**Comment by sangnguyenz** [comment]
> You would have to modify multiple files. Definitely `experiments/scripts/test_tracktor.py` and `src/tracktor/tracker.py`. It is definitely possible to switch out the underlying Faster-RCNN implementation but there is probably some work involved.

After taking a look at those 2 files, I'm not sure that I understand how you can get the data to put in the network. Now I'm working with Pytorch 1.0, so I can not produce blob data as the way you did. Can I put the frame as image or image array to **tracker.step(frame)** of the tracker (supposed that I've done get detection step).?

Thank you.

**Comment by timmeinhardt** [comment]
Without testing PyTorch 1.0 by myself I think that the data blobs should still be produced as before, i.e, the `Tracker.step` method receives a `blob` argument which includes the data, ground truth and some image information. 
In order to use a different object detector (our detector will not work with PyTorch 1.0), you have to provide the same interface as ours. See `self.obj_detect.load_image` and `self.obj_detect.test_rois` and the corresponding functions in `src/tracktor/fpn.py`.

**Comment by idmakers** [comment]
Hello ! I already have a detect data , and I want to use my own data .How can I do it?

**Comment by timmeinhardt** [comment]
We just updated the repository to support PyTorch 1.3 and added a new object detector. I did some rudimentary testing but feel free to give me feedback if something is not working as before.

I will close this issue. Please open new issues if something is broken now.
