### ISSUE TITLE
Fix understanding about this project

### ISSUE THREAD

**Issue by rose-jinyang** [phil-bergmann/tracking_wo_bnw#72]
Hi
Thanks for contributing this paper and code.
I've just looked at the paper and project source code.
I have some questions.
I understood that Tracktor uses only a detector based on Faster-RCNN&FPN and Tracktor++ uses the detector as well as motion model and re-ID model too.
Is that right?
Thanks

**Comment by timmeinhardt** [comment]
Yes, this is right. The motion model of Tracktor++ comes in form of a CMC camera motion compensation.

**Comment by timmeinhardt** [comment]
Can we close this issue?
