### ISSUE TITLE
Tracking  cars

### ISSUE THREAD

**Issue by young-yangb** [phil-bergmann/tracking_wo_bnw#73]
Hello,

thanks for your great work.

If I want to apply your project in tracking cars, what should I do? maybe just change the reid part? 
I have noticed that the default reid weights is "ResNet_iter_25245.pth", maybe I should train resnet in a car dataset and then replace that. 

Any details should I pay attention to? Thank you very much!

**Comment by timmeinhardt** [comment]
Yes, you should retrain the object detector and if possible the reID network on your car dataset. In order to train the reID network you need some form of tracking ground truth data for cars.

**Comment by young-yangb** [comment]
Thank you for your reply!

And I still want to make sure some details:

(1) about retrain object detector: Your project doesn't contain object detector part, right?  So I can imitate your training process on Google Colab notebook and add the code about detector to the original project. After that I can retrain my object detector.

(2)In your reply, you mentioned that" if possible retrain the reID network", which means even if  I don't change the reID weights, it still work, and maybe just with not so good performance? 

Thank you！！

**Comment by timmeinhardt** [comment]
(1) the repository provides an object detector model file trained on MOT17 and tracktor which applied the detector. the training was done with the colab notebook.

(2) yes. it might work but with suboptimal performance.

**Comment by young-yangb** [comment]
Thank you very much : )

> (1) the repository provides an object detector model file trained on MOT17 and tracktor which applied the detector. the training was done with the colab notebook.
> (2) yes. it might work but with suboptimal performance.
