### ISSUE TITLE
A question about MOT17 test  dataset

### ISSUE THREAD

**Issue by TTTREE** [phil-bergmann/tracking_wo_bnw#77]
Hi,
Thanks for your nice work!!
I am trying to upload my results of MOT17 generated by this code to MOT Challenge test sever. I have got the results of the mot17 test dataset, like MOT17-01, MOT17-03, but it seems I need to upload the results of the training dataset together. Like MOT17-02, MOT17-04, MOT17-05...
![图片](https://user-images.githubusercontent.com/37862384/79762117-e45ccd00-8354-11ea-8b24-3d5e103bb782.png)

So do I need to also generate the results of the MOT17 train dataset using this code, or just upload the "gt.txt" of the training dataset without running on our tracker.
Could you please figure me out? 
Thanks a lot!

**Comment by timmeinhardt** [comment]
In theory yes, you could upload the training GT just to get the evaluation running. But this is in violation with the MOTChallenge submission rules. Once you publish a tracker your training results will be provided as well. This facilitates ablation studies and other comparisons for other researchers.

**Comment by TTTREE** [comment]
> 
> 
> In theory yes, you could upload the training GT just to get the evaluation running. But this is in violation with the MOTChallenge submission rules. Once you publish a tracker your training results will be provided to the public as well. This facilitates ablation studies and other comparisons for other researchers.

Thanks for your kind and prompt reply!！
Is that mean the training results will not participate in the MOT17 test process. So no matter what training result I submit, it will not affect the final test results?

**Comment by timmeinhardt** [comment]
Yes, it will not effect the test results. However, uploading GT other training results is in violation with the MOTChallenge submission rules.

**Comment by TTTREE** [comment]
> 
> 
> Yes, it will not effect the test results. However, uploading GT other training results is in violation with the MOTChallenge submission rules.

Get it! Thanks u very much!
