### ISSUE TITLE
A question about director

### ISSUE THREAD

**Issue by Huwenzjw** [phil-bergmann/tracking_wo_bnw#80]
Thanks for your wonderful job.I have a question about your bounding boxes.
      I read your papers and know you use the fixed bounding boxes to predict bounding boxes in the next frame. 
    And for the untracked public boxes，you also make some realigement to public boxes. 
    And finally，you use iou to track.So I wonder if I do not predict bounding boxes in the next frame，I just make some realignment to public boxes in every frame.And between two frames，I use iou to track. Is the result as good as your job？ Thanks Again

**Comment by timmeinhardt** [comment]
I am not sure if I understood you correctly but we are NOT doing tracking with IoU. We use IoU to initialize and kill tracks but the general tracking is done via regression of the previous boundnig box to the object's new position.

**Comment by Huwenzjw** [comment]
ok,I have misunderstood your papers before I read your answer.Thanks very much.your work is wonderful. You are geniuses

**Comment by timmeinhardt** [comment]
Thank you, we are glad to hear that our work is useful for you. Can we close this issue?

**Comment by Huwenzjw** [comment]
yes，you can
