### ISSUE TITLE
How to train my own model.

### ISSUE THREAD

**Issue by em-visual-language** [phil-bergmann/tracking_wo_bnw#81]
Hi, thanks for your brilliant work. 

I wonderer how can I train the basic Tracktor without considering the reid and motion effect?

**Comment by timmeinhardt** [comment]
Hello, please follow our paper, the README.md and various issues in this repository on how to train Tracktor (an object detector) on your own dataset.

**Comment by timmeinhardt** [comment]
Can we close this issue?
