### ISSUE TITLE
prompt-toolkit version error

### ISSUE THREAD

**Issue by 2a2a** [phil-bergmann/tracking_wo_bnw#84]
The prompt-toolkit version provide in requirements.txt is 1.0.18
`ERROR: jupyter-console 6.0.0 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.18 which is incompatible.`
When I use higher version
`ERROR: ipython 5.5.0 has requirement prompt-toolkit<2.0.0,>=1.0.4, but you'll have prompt-toolkit 2.0.1 which is incompatible.`
So, which version should I change...
And is lapsolver package necessary? It always exists error when install with other packages in requirements.txt
Thx

**Comment by timmeinhardt** [comment]
For which Python version are you installing the packages?

**Comment by 2a2a** [comment]
> For which Python version are you installing the packages?

3.6

**Comment by 2a2a** [comment]
It's not a big problem now, so I close this issue, thanks for reply.
