### ISSUE TITLE
Does test_tracktor.py detect and add new boxes that are not included in the public detection?

### ISSUE THREAD

**Issue by igygi** [phil-bergmann/tracking_wo_bnw#85]
Hi, 

I'd like to clarify whether the algorithm detects new boxes (not included in the public detection set) as well during inference, aside from regressing the positions of the boxes in the public detection set. 

For example, what happens if in frame t+1, a bounding box in frame t is regressed to position (x1, y1, x2, y2) but in the public detection set, there is no bounding box in frame t+1 that intersects with this regressed position?

Thank you.

**Comment by timmeinhardt** [comment]
Hello, thank you for your interest in our research. If applied with public detections our Tracktor framework starts any regression only with bounding box form the set of public detections. However, as you described, it is possible for the regression to produce bounding boxes in subsequent frames which do not intersect with any of the public detections in that particular frame. We had some discussions regarding the "publicness" of our method in #24 .

**Comment by igygi** [comment]
This is understood. Thanks so much @timmeinhardt for your help and for this wonderful work.
