### ISSUE TITLE
ResNet seems to give different embeddings across different runs

### ISSUE THREAD

**Issue by suxuann** [phil-bergmann/tracking_wo_bnw#86]
I tried to run the ReID network on two different sets of boxes, as shown in the following code.

`dets = torch.tensor([[1337., 417., 1503., 795.]])`
`embeddings = self.reid_network.test_rois(image, dets).data`

and,

`dets = torch.tensor([[1337., 417., 1503., 795.], [585., 446., 669., 708.]])`
`embeddings = self.reid_network.test_rois(image, dets).data`

It seems like the resulting embeddings for the box `[1337., 417., 1503., 795.]` are different in the two runs. Could you kindly help me verify if this is the case?

**Comment by timmeinhardt** [comment]
I just did a quick check and the embeddings seemed to be the same for different runs. You can also see how we set the random seeds and CUDNN backend to deterministic in `test_tracktor.py`.  How do you measure the similarity of embeddings?

**Comment by suxuann** [comment]
Hello, I checked again. The embeddings are the same. Thank you.

**Comment by timmeinhardt** [comment]
Okay. I will close this issue.
