### ISSUE TITLE
Wrong weights model?

### ISSUE THREAD

**Issue by agirbau** [phil-bergmann/tracking_wo_bnw#87]
First of all, thank you for the very nice work!

I was trying to reproduce the results of tracktor++2, and I got these for training sequences:

          IDF1   IDP   IDR  Rcll  Prcn  GT  MT  PT  ML  FP    FN IDs   FM  MOTA  MOTP
OVERALL        65.0% 84.0% 53.1% 62.6% 99.0% 546 194 238 114 694 42031 292  412 **61.7%** 0.106

I tried months ago with tracktor++, and got the same results. Could it be that the uploaded model in the Readme is not the same model you used in tracktor++2?

**Comment by timmeinhardt** [comment]
I just double checked the zip file and it includes the correct model file. Are you using the model file from [this](https://vision.in.tum.de/webshare/u/meinhard/tracking_wo_bnw-output_v2.zip) file?

**Comment by agirbau** [comment]
I'm testing the tracktor on another machine, just to make a double check. I'll post the results in an hour or so.

**Comment by agirbau** [comment]
Yes, I tried with both computers (with different GPUs) the master branch and both gave the same results:

OVERALL        65.0% 84.0% 53.1% 62.6% 99.0% 546 194 238 114 694 42031 292  412 61.7% 0.106

If it's not in the weights, maybe the configuration was different?

**Comment by timmeinhardt** [comment]
Is it possible that these are the results only on the Faster R-CNN public detections and not averaged over all three sets (DPM, Faster R-CNN, SDP0?

**Comment by agirbau** [comment]
Yes, I think so. How should I average them?

**Comment by agirbau** [comment]
Ok, by using the correct configuration the results are finally

OVERALL        65.1% 83.7% 53.3% 63.1% 99.1% 1638 556 710 372 1891 124450 896  1292 62.2% 0.105

Thanks!
