### ISSUE TITLE
can i run in windows?

### ISSUE THREAD

**Issue by xiaoliyong** [phil-bergmann/tracking_wo_bnw#9]

**Comment by timmeinhardt** [comment]
Our method should run on Linus and OSX. I am not familiar enough with Python and PyTorch in the Windows ecosystem.

**Comment by xiaoliyong** [comment]
@timmeinhardt  Thanks your answer!  When can you update pytorch 1.0+?

**Comment by timmeinhardt** [comment]
This update is currently not planned. However, we are happy to receive pull requests.

**Comment by timmeinhardt** [comment]
Can we close this issue?
