### ISSUE TITLE
Regressing to bounding box position in next frame: Training vs Inference

### ISSUE THREAD

**Issue by igygi** [phil-bergmann/tracking_wo_bnw#91]
Hi, 

I would like to clarify something about the detector training. The paper says that Tracktor performs frame-to-frame tracking by regressing the location of an existing track to its location in the next frame. 

Looking at the code, is my understanding correct that during **training**,  you are training a regular Faster-RCNN detector (regressing to an object location in the **current** frame) and that the "regression to the position in the next frame" only happens during inference time? 

If this is correct, that means when training on my own dataset, I can simply train my detector on an object detection dataset that contains "independent" images (no need for consecutive frames)? 

Thank you.

**Comment by timmeinhardt** [comment]
Yes, your understanding is correct. We train the regression on single frame object detection and this generalizes to frame-to-frame object tracking. However, as detailed in the paper this has some limitation regarding the frame rate/camera motion, i.e., if the object moves so much from frame to frame that the previous bounding box does not contain parts of the current frame object position the regression will not be able to recover. To mitigate this we applied camera motion compensation, identification and a constant velocity motion model.

**Comment by timmeinhardt** [comment]
Can we close this issue?

**Comment by igygi** [comment]
yes, thank you for clearing this out!
