### ISSUE TITLE
Calculating MODA and MODP scores

### ISSUE THREAD

**Issue by Sentient07** [phil-bergmann/tracking_wo_bnw#93]
Hello Phil and Tim,

Thank you for the research and open sourcing the code. Could you please help me understand how to compute MODA and MODP scores? One way I see is to submit to the official MOT Challenge benchmark, but is there code available for the same, which I can use on my data to get the above mentioned measures?

Thank you for your time,

Regards,
Ramana

**Comment by timmeinhardt** [comment]
Hello Ramana, the repository includes the `motmetrics` package which calculates most of the necessary metrics. If you want compute the exact metrics from the MOTChallenge you should download their [devikt](https://motchallenge.net/devkit/) which reads the prediction files and processes them like they it is done on the server.

**Comment by Sentient07** [comment]
Hi Tim,

Thank you for referring to the repository. I will evaluate with that tool.

Regards,
