### ISSUE TITLE
the issue of  run tracker.py  

### ISSUE THREAD

**Issue by feidasheng** [phil-bergmann/tracking_wo_bnw#97]
![image](https://user-images.githubusercontent.com/44360716/88609150-fe295100-d0b5-11ea-82e7-50f1f287b9f5.png)
hello，what I want to ask is why I run the run.tracker.py file, why does the data set of running mot17 have no indicators displayed, my data set and reid model are both loaded ，ths.

**Comment by feidasheng** [comment]
i run test_tracktor.py

**Comment by timmeinhardt** [comment]
I think this comes from your dataset not being at the correct place. Have you fixed the issue?

**Comment by timmeinhardt** [comment]
Can we close this issue?
