### ISSUE TITLE
How to use Tracktor Inferences

### ISSUE THREAD

**Issue by itruonghai** [phil-bergmann/tracking_wo_bnw#99]
Can I use only tracktor inferences to track (assume that we already has bounding, score and class)?

**Comment by timmeinhardt** [comment]
Hello, you probably have to change our code to your needs (and inputs) but yes that should be possible.

**Comment by capricornfati** [comment]
@itruonghai Were you able to track based on given detections and images?

**Comment by capricornfati** [comment]
What I would like to track is not pedestrian, I want to track cars on the road. Is it possible to track with detections and images as well?

**Comment by timmeinhardt** [comment]
In order to track cars, you have to train the object detector for cars and/or pedestrians. Can we close this issue?
